In [2]:
import pandas as pd

df = pd.read_csv('avocado_df.csv', index_col=0)

display(df)

,region,AveragePrice,Total Volume,co-ordinates,latitude,longitude,geometry
0,Albany,1.561036,4.753787e+04,"(42.65155029296875, -73.75521087646484)",42.651550,-73.755211,POINT (-73.75521087646484 42.65155029296875)
1,Atlanta,1.337959,2.621453e+05,"(33.74831008911133, -84.39111328125)",33.748310,-84.391113,POINT (-84.39111328125 33.74831008911133)
2,BaltimoreWashington,1.534231,3.985619e+05,"(39.183738708496094, -76.67420959472656)",39.183739,-76.674210,POINT (-76.67420959472656 39.18373870849609)
3,Boise,1.348136,4.264257e+04,"(43.60763931274414, -116.19339752197266)",43.607639,-116.193398,POINT (-116.1933975219727 43.60763931274414)
4,Boston,1.530888,2.877929e+05,"(42.35866165161133, -71.0567398071289)",42.358662,-71.056740,POINT (-71.05673980712891 42.35866165161133)
5,BuffaloRochester,1.516834,6.793630e+04,"(42.885440826416016, -78.87846374511719)",42.885441,-78.878464,POINT (-78.87846374511719 42.88544082641602)
6,California,1.395325,3.044324e+06,"(37.25510025024414, -119.61752319335938)",37.255100,-119.617523,POINT (-119.6175231933594 37.25510025024414)
7,Charlotte,1.606036,1.051939e+05,"(35.22285842895508, -80.83795928955078)",35.222858,-80.837959,POINT (-80.83795928955078 35.22285842895508)
8,Chicago,1.556775,3.955690e+05,"(41.88425064086914, -87.6324462890625)",41.884251,-87.632446,POINT (-87.6324462890625 41.88425064086914)
9,CincinnatiDayton,1.209201,1.317219e+05,"(39.10712814331055, -84.5041275024414)",39.107128,-84.504128,POINT (-84.50412750244141 39.10712814331055)
10,Columbus,1.252781,8.873776e+04,"(39.96199035644531, -83.00274658203125)",39.961990,-83.002747,POINT (-83.00274658203125 39.96199035644531)
11,DallasFtWorth,1.085592,6.166251e+05,"(32.778221130371094, -96.79512023925781)",32.778221,-96.795120,POINT (-96.79512023925781 32.77822113037109)
12,Denver,1.218580,4.109542e+05,"(39.74000930786133, -104.99201965332031)",39.740009,-104.992020,POINT (-104.9920196533203 39.74000930786133)
13,Detroit,1.276095,1.876403e+05,"(42.33168029785156, -83.0479965209961)",42.331680,-83.047997,POINT (-83.04799652099609 42.33168029785156)
14,GrandRapids,1.505000,8.938383e+04,"(42.9664192199707, -85.67195129394531)",42.966419,-85.671951,POINT (-85.67195129394531 42.9664192199707)
16,HarrisburgScranton,1.513284,1.236948e+05,"(40.25986099243164, -76.88223266601562)",40.259861,-76.882233,POINT (-76.88223266601563 40.25986099243164)
17,HartfordSpringfield,1.818639,1.499128e+05,"(39.801300048828125, -89.64360046386719)",39.801300,-89.643600,POINT (-89.64360046386719 39.80130004882813)
18,Houston,1.047929,6.010884e+05,"(29.76058006286621, -95.36968231201172)",29.760580,-95.369682,POINT (-95.36968231201172 29.76058006286621)
19,Indianapolis,1.313994,8.953666e+04,"(39.766910552978516, -86.14996337890625)",39.766911,-86.149963,POINT (-86.14996337890625 39.76691055297852)
20,Jacksonville,1.510947,8.517753e+04,"(30.331470489501953, -81.65621948242188)",30.331470,-81.656219,POINT (-81.65621948242188 30.33147048950195)
21,LasVegas,1.380917,1.608784e+05,"(36.17192840576172, -115.14000701904297)",36.171928,-115.140007,POINT (-115.140007019043 36.17192840576172)
22,LosAngeles,1.216006,1.502653e+06,"(34.053489685058594, -118.24532318115234)",34.053490,-118.245323,POINT (-118.2453231811523 34.05348968505859)
23,Louisville,1.286686,4.762427e+04,"(38.25489044189453, -85.76666259765625)",38.254890,-85.766663,POINT (-85.76666259765625 38.25489044189453)
24,MiamiFtLauderdale,1.428491,2.889740e+05,"(25.790729522705078, -80.16264343261719)",25.790730,-80.162643,POINT (-80.16264343261719 25.79072952270508)
26,Nashville,1.212101,1.053612e+05,"(36.16783905029297, -86.77816009521484)",36.167839,-86.778160,POINT (-86.77816009521484 36.16783905029297)
27,NewOrleansMobile,1.304793,1.351927e+05,"(29.953699111938477, -90.07775115966797)",29.953699,-90.077751,POINT (-90.07775115966797 29.95369911193848)
28,NewYork,1.727574,7.122311e+05,"(40.71455001831055, -74.00714111328125)",40.714550,-74.007141,POINT (-74.00714111328125 40.71455001831055)
30,NorthernNewEngland,1.477396,2.116358e+05,"(44.08305740356445, -70.5822982788086)",44.083057,-70.582298,POINT (-70.58229827880859 44.08305740356445)
31,Orlando,1.506213,1.735524e+05,"(28.538230895996094, -81.37738800048828)",28.538231,-81.377388,POINT (-81.37738800048828 28.53823089599609)
32,Philadelphia,1.632130,2.125408e+05,"(39.95222091674805, -75.16217803955078)",39.952221,-75.162178,POINT (-75.16217803955078 39.95222091674805)
33,PhoenixTucson,1.224438,5.788264e+05,"(33.44824981689453, -112.07579803466797)",33.448250,-112.075798,POINT (-112.075798034668 33.44824981689453)
34,Pittsburgh,1.364320,5.564008e+04,"(40.43851089477539, -79.9973373413086)",40.438511,-79.997337,POINT (-79.99733734130859 40.43851089477539)
36,Portland,1.317722,3.270775e+05,"(45.51179122924805, -122.67562866210938)",45.511791,-122.675629,POINT (-122.6756286621094 45.51179122924805)
37,RaleighGreensboro,1.555118,1.426116e+05,"(35.78548812866211, -78.6427230834961)",35.785488,-78.642723,POINT (-78.64272308349609 35.78548812866211)
38,RichmondNorfolk,1.291331,1.249433e+05,"(37.540679931640625, -77.43367004394531)",37.540680,-77.433670,POINT (-77.43367004394531 37.54067993164063)
39,Roanoke,1.247929,7.408879e+04,"(37.27151870727539, -79.94056701660156)",37.271519,-79.940567,POINT (-79.94056701660156 37.27151870727539)
40,Sacramento,1.621568,2.223779e+05,"(38.57944107055664, -121.49085235595703)",38.579441,-121.490852,POINT (-121.490852355957 38.57944107055664)
41,SanDiego,1.398166,2.656566e+05,"(32.71567916870117, -117.16171264648438)",32.715679,-117.161713,POINT (-117.1617126464844 32.71567916870117)
42,SanFrancisco,1.804201,4.018645e+05,"(37.77711868286133, -122.41963958740234)",37.777119,-122.419640,POINT (-122.4196395874023 37.77711868286133)
43,Seattle,1.442574,3.231189e+05,"(47.60356903076172, -122.32945251464844)",47.603569,-122.329453,POINT (-122.3294525146484 47.60356903076172)
44,SouthCarolina,1.403284,1.797449e+05,"(33.90385437011719, -80.89376831054688)",33.903854,-80.893768,POINT (-80.89376831054688 33.90385437011719)
47,Spokane,1.445592,4.605111e+04,"(47.65726089477539, -117.41227722167969)",47.657261,-117.412277,POINT (-117.4122772216797 47.65726089477539)
48,StLouis,1.430621,9.489004e+04,"(38.627750396728516, -90.1995620727539)",38.627750,-90.199562,POINT (-90.19956207275391 38.62775039672852)
49,Syracuse,1.520325,3.237476e+04,"(43.050418853759766, -76.14737701416016)",43.050419,-76.147377,POINT (-76.14737701416016 43.05041885375977)
50,Tampa,1.408846,1.952797e+05,"(27.946529388427734, -82.45926666259766)",27.946529,-82.459267,POINT (-82.45926666259766 27.94652938842773)
53,WestTexNewMexico,1.261701,4.314085e+05,"(34.421321868896484, -106.10840606689453)",34.421322,-106.108406,POINT (-106.1084060668945 34.42132186889648)

In [ ]:
from bokeh.io import output_notebook, show, output_file, output_html
from bokeh.plotting import figure, ColumnDataSource
from bokeh.tile_providers import get_provider, CARTODBPOSITRON
from bokeh.palettes import PRGn, RdYlGn
from bokeh.transform import linear_cmap,factor_cmap
from bokeh.layouts import row, column
from bokeh.models import GeoJSONDataSource, LinearColorMapper, ColorBar, NumeralTickFormatter

import numpy as np


# Define function to switch from lat/long to mercator coordinates
def x_coord(x, y):
    
    lat = x
    lon = y
    
    r_major = 6378137.000
    x = r_major * np.radians(lon)
    scale = x/lon
    y = 180.0/np.pi * np.log(np.tan(np.pi/4.0 + 
        lat * (np.pi/180.0)/2.0)) * scale
    return (x, y)




# Obtain list of mercator coordinates
mercators = [x_coord(x, y) for x, y in df['co-ordinates'] ]

# Create column mercator
df['mercator'] = mercators

# Define columns mercator_x and mercator_y
df[['mercator_x', 'mercator_y']] = df['mercator'].apply(pd.Series)

# Drop 'geometry' column 
df = df.drop(columns=['geometry'])

# Preview
df.head()

In [ ]:
# Create map with Bokeh

# Set underlying map
chosentile = get_provider(CARTODBPOSITRON)

# Set palette
palette = PRGn[11]

# Set source to df
source = ColumnDataSource(data=df)

# Define color mapper
color_mapper = linear_cmap(field_name = 'AveragePrice', palette = palette, low = df['AveragePrice'].min(), high = df['AveragePrice'].max())

# Set tooltips
nan_color = '#d9d9d9'
tooltips = [("Price","@AveragePrice"), ("Region","@region")]


# Create figure
p = figure(title = 'Avocado Prices by region in the United States', x_axis_type="mercator", y_axis_type="mercator", 
           x_axis_label = 'Longitude', y_axis_label = 'Latitude', tooltips = tooltips)

# Add map tile
p.add_tile(chosentile)

# Add points using mercator coordinates
p.circle(x = 'mercator_x', y = 'mercator_y', color = color_mapper, source=source, size=30, fill_alpha = 0.7)

#Defines color bar
color_bar = ColorBar(color_mapper=color_mapper['transform'], 
                     formatter = NumeralTickFormatter(format='0.0[0000]'), 
                     label_standoff = 13, width=8, location=(0,0))

# Set color_bar location
p.add_layout(color_bar, 'right')

# Display in notebook
output_notebook()

# Save as HTML
output_file('avocado.html', title='Avocado Prices by region in the United States')

# Show map
show(p)